_core:
  default_config_hash: EspchZru2hYTTeNNAnTw2uWwT-mjJ46KrM5XEVHJzS0
langcode: en
uuid: 1c93228a-721f-4e88-bdf3-8a5ca8f12c60
popup_enabled: true
popup_clicking_confirmation: false
popup_scrolling_confirmation: false
eu_only: null
eu_only_js: null
popup_position: false
fixed_top_position: true
popup_info:
  value: "<p><strong>We use cookies to improve user experience, analyze website traffic, and provide social media services.</strong> We may share your site usage data with our analytics partners. By continuing to the site, you consent to store on your device all the technologies described in our Cookie Policy. Please read our <a href=\"https://www.iubenda.com/privacy-policy/482469/legal\">privacy policy</a> for full details.</p>\r\n"
  format: basic_html
mobile_popup_info:
  value: ''
  format: basic_html
popup_info_template: new
popup_agree_button_message: Ok
popup_more_info_button_message: 'More info'
mobile_breakpoint: 768
popup_agreed_enabled: false
popup_hide_agreed: false
disagree_button_label: Nothing
popup_agreed:
  value: "<h2>Thank you for accepting cookies</h2>\r\n\r\n<p>You can now hide this message or find out more about cookies.</p>\r\n"
  format: basic_html
popup_find_more_button_message: 'More info'
popup_hide_button_message: Hide
popup_link: 'https://www.iubenda.com/privacy-policy/482469'
popup_link_new_window: true
popup_height: null
popup_width: ''
popup_delay: 0
show_more_info: false
popup_bg_hex: ''
popup_text_hex: ''
domain: ''
domains_option: 1
domains_list: ''
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
exclude_admin_theme: true
cookie_session: 0
set_cookie_session_zero_on_disagree: 0
cookie_lifetime: 100
use_mobile_message: false
use_bare_css: true
disagree_do_not_show_popup: false
reload_page: false
reload_options: 0
reload_routes_list: ''
cookie_name: ''
exclude_uid_1: true
better_support_for_screen_readers: false
method: opt_in
disabled_javascripts: ''
automatic_cookies_removal: true
allowed_cookies: ''
consent_storage_method: basic
withdraw_message:
  value: "<h2>We use cookies on this site to enhance your user experience</h2>\r\n\r\n<p>You have given your consent for us to set cookies.</p>\r\n"
  format: basic_html
withdraw_tab_button_label: 'Privacy settings'
withdraw_action_button_label: 'Withdraw consent'
withdraw_enabled: false
withdraw_button_on_info_popup: false
save_preferences_button_label: 'Save preferences'
accept_all_categories_button_label: 'Accept all cookies'
enable_save_preferences_button: true
domain_all_sites: false
settings_tab_enabled: false
containing_element: body
cookie_policy_version: 1.0.0
cookie_value_disagreed: '0'
cookie_value_agreed_show_thank_you: '1'
cookie_value_agreed: '2'
accessibility_focus: false
