_core:
  default_config_hash: ViXe1Mhsdfc0AY1y-5R7vwxUoVItsnRfbQbQYzQGEEs
api_key: bd47eb75d0b4475936878948b3c0e0ba-us14
api_timeout: 10
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
enable_connected: false
connected_id: null
connected_paths: null
webhook_hash: b2ad46959e6394d28d496d3f005be650
